# Generated by Django 2.2 on 2023-07-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.BigIntegerField()),
                ('Password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductImage', models.CharField(max_length=255)),
                ('ProductPrice', models.BigIntegerField()),
                ('ProductOffer', models.BooleanField()),
                ('OfferPrice', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('UserEmail', models.EmailField(max_length=255)),
                ('UserMobile', models.BigIntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('PaymentMethod', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalPrice', models.BigIntegerField()),
                ('TotalQuantity', models.BigIntegerField()),
                ('OrderDate', models.DateTimeField(auto_now=True, verbose_name='')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalQantity', models.BigIntegerField(default=0)),
                ('TotalPrice', models.BigIntegerField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Product')),
            ],
        ),
    ]
